export const wordList = {
    carro: ["automóvel", "veículo", "meio de transporte", "roda", "motor", "direção", "estrada"],
    livro: ["obra", "publicação", "texto", "leitura", "capa", "páginas", "escrito"],
    casa: ["residência", "habitação", "moradia", "lar", "morador", "teto", "quarto"],
    computador: ["máquina", "PC", "hardware", "software", "tecnologia", "digital", "trabalho"],
    telefone: ["celular", "móvel", "comunicação", "chamada", "telefone", "ligações", "rede"],
    mesa: ["móvel", "superfície", "mesa de jantar", "tabela", "escrivaninha", "peça de mobiliário", "design"],
    cadeira: ["assento", "móvel", "revestimento", "encosto", "estofado", "design", "decoração"],
    janela: ["abertura", "vidro", "painel", "claridade", "vista", "abertura para o exterior", "quadro"],
    porta: ["entrada", "fechadura", "móvel", "abertura", "tranca", "passagem", "acesso"],
    jardim: ["espaço verde", "horta", "plantas", "flores", "paisagismo", "área externa", "decoração"],
    caneta: ["instrumento de escrita", "esferográfica", "tinta", "escrever", "material de escritório", "bolsa", "cap"],
    papel: ["folha", "documento", "escritura", "impressão", "material de escritório", "leitura", "cópia"],
    carteira: ["bolso", "acessório", "dinheiro", "documentos", "couro", "porta-moedas", "cartões"],
    escola: ["instituição", "educação", "aprendizado", "professores", "alunos", "aulas", "ensino"],
    professor: ["educador", "instrutor", "ensinamento", "aulas", "escola", "mentor", "sabedoria"],
    aluno: ["estudante", "discente", "escola", "aprendiz", "aula", "notas", "dever de casa"],
    festa: ["celebração", "evento", "música", "dança", "comida", "convidados", "diversão"],
    música: ["melodia", "canção", "notas", "instrumentos", "ritmo", "som", "áudio"],
    chave: ["instrumento", "fechadura", "abrir", "porta", "tranca", "segurança", "chaveiro"],
    relógio: ["hora", "tempo", "pulso", "acessório", "cronômetro", "relógio de pulso", "marcador"],
    pintura: ["arte", "tela", "cor", "pincel", "obra", "quadrado", "canvas"],
    quadro: ["imagem", "tela", "moldura", "decoração", "pintura", "foto", "painel"],
    televisão: ["TV", "aparelho", "imagem", "som", "programas", "entretenimento", "canal"],
    camisa: ["roupa", "vestuário", "manga", "tecido", "botão", "colina", "moda"],
    calça: ["roupa", "vestuário", "pernas", "tecido", "cintura", "moda", "calça jeans"],
    sapato: ["calçado", "pés", "moda", "solado", "couro", "uso diário", "conforto"],
    chuva: ["precipitação", "água", "tempo", "nublado", "gotejamento", "umidade", "clima"],
    sol: ["estrela", "astro", "luz", "calor", "dia", "energia", "brilho"],
    lua: ["satélite", "astro", "noite", "fase", "crescimento", "beleza", "reflexo"],
    estrela: ["corpo celeste", "astro", "brilho", "constelação", "noite", "galáxia", "luz"],
    mar: ["oceano", "água", "praia", "ondas", "sal", "profundidade", "navegação"],
    rio: ["correnteza", "água", "fluvial", "navegação", "curso d'água", "peixe", "recurso"],
    lago: ["corpo d'água", "espelho d'água", "área tranquila", "natureza", "fauna", "vegetação", "nadar"],
    montanha: ["elevação", "serra", "pico", "altitude", "rocha", "escalada", "natureza"],
    planície: ["campo", "área plana", "vegetação", "agricultura", "paisagem", "terreno", "lago"],
    floresta: ["bosque", "vegetação", "árvores", "fauna", "ecosistema", "natureza", "madeira"],
    deserto: ["areia", "área árida", "calor", "oásis", "secura", "duna", "desolado"],
    viagem: ["deslocamento", "trabalho", "turismo", "passagem", "destino", "transporte", "exploração"],
    hotel: ["acomodação", "hospedagem", "quarto", "serviço", "reservas", "estadia", "luxo"],
    restaurante: ["lugar para comer", "refeitório", "cardápio", "pratos", "comida", "serviço", "clientes"],
    loja: ["comércio", "estabelecimento", "compras", "produtos", "vendas", "atendimento", "preço"],
    mercado: ["supermercado", "feira", "produtos", "alimentos", "compras", "bazar", "preços"],
    farmácia: ["drogaria", "medicamentos", "remédios", "saúde", "prescrição", "tratamento", "cura"],
    hospital: ["clínica", "unidade de saúde", "medicamentos", "tratamento", "internação", "enfermeiros", "médicos"],
    médico: ["profissional", "especialista", "consultório", "tratamento", "diagnóstico", "prescrição", "medicamentos"],
    enfermeiro: ["assistente de saúde", "cuidador", "hospital", "pacientes", "tratamento", "medicamentos", "suporte"],
    cirurgia: ["operação", "procedimento", "médico", "anestesia", "incisão", "recuperação", "hospital"],
    medicamento: ["remédio", "droga", "tratamento", "prescrição", "farmácia", "cura", "saúde"],
    vacina: ["imunização", "preventivo", "injeção", "doença", "proteção", "doses", "imunidade"],
    odontologia: ["dentística", "cuidados dentários", "dentista", "consultório", "dental", "prevenção", "higiene"],
    dentista: ["profissional de dentes", "consultório", "tratamento dental", "higiene", "odontologia", "cuidar", "exame"],
    esporte: ["atividade física", "jogo", "competição", "treinamento", "atleta", "saúde", "lazer"],
    futebol: ["soccer", "bola", "times", "goleiro", "gols", "campo", "esporte"],
    basquete: ["jogo de bola", "cesta", "time", "quadra", "drible", "arremesso", "esporte"],
    natação: ["atividade", "esporte", "piscina", "nadar", "estilos", "água"]
}